In [1]:
import pandas as pd
import pandas as pd
from sqlalchemy import create_engine


engine = create_engine(
    "mysql+pymysql://root:vedant_07@localhost:3306/customer_shopping_behaviour"
)

In [2]:
data = pd.read_csv('customer_shopping_behavior.csv')

In [20]:
data.to_sql(
    "customer_shopping",
    con=engine,
    if_exists="replace",
    index=False
)

3900

In [6]:
data.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
data['Review Rating']= data.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [8]:
data.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
data.columns = data.columns.str.lower()
data.columns = data.columns.str.replace(' ','_')
data = data.rename(columns ={'purchase_amount_(usd)':'purchase_amount'})

# create a column age group

In [11]:
labels = ['Young adult','adult','middle-aged','seniors']
data['age_group'] = pd.qcut(data['age'], q=4 ,labels = labels)

In [12]:
data[['age','age_group']].head(10)

   age    age_group
0   55  middle-aged
1   19  Young adult
2   50  middle-aged
3   21  Young adult
4   45  middle-aged
5   46  middle-aged
6   63      seniors
7   27  Young adult
8   26  Young adult
9   57  middle-aged

# purchase frequnecy_days

In [13]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

data['purchase_frequency_days']=data['frequency_of_purchases'].map(frequency_mapping)

In [14]:
data[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [15]:
data[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [16]:
(data['discount_applied' ]== data['promo_code_used']).all()

np.True_

In [17]:
data = data.drop('promo_code_used',axis=1)

In [18]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [19]:
data.to_sql(
    "customer_shopping",
    con=engine,
    if_exists="replace",
    index=False
)

3900